// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jdbnfbtuaueicsumetrw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpkYm5mYnR1YXVlaWNzdW1ldHJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzMzgzMzUsImV4cCI6MjA1ODkxNDMzNX0.bM-JMNV6SFVrjMjg0NYq_7pEmIgohGlCdOiM5_F7IU4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);